version: '3.8'

services:
  plane-db:
    image: docker.io/library/postgres:15-alpine
    container_name: plane-db
    restart: always
    environment:
      POSTGRES_USER: plane
      POSTGRES_PASSWORD: plane_password
      POSTGRES_DB: plane
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /media/large_disk/Projects/depoly/plane_data/pg_data:/var/lib/postgresql/data:Z
    networks:
      - plane_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plane -d plane"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  plane-redis:
    image: docker.io/library/redis:7-alpine
    container_name: plane-redis
    restart: always
    volumes:
      - /media/large_disk/Projects/depoly/plane_data/redis_data:/data:Z
    networks:
      - plane_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  plane-minio:
    image: docker.io/minio/minio
    container_name: plane-minio
    restart: always
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: plane-admin
      MINIO_ROOT_PASSWORD: plane-secret-key-123
    volumes:
      - /media/large_disk/Projects/depoly/plane_data/minio_data:/data:Z
    networks:
      - plane_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  plane-createbuckets:
    image: docker.io/minio/mc
    container_name: plane-createbuckets
    depends_on:
      plane-minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://plane-minio:9000 plane-admin plane-secret-key-123;
      /usr/bin/mc mb myminio/plane-uploads --ignore-existing;
      /usr/bin/mc anonymous set download myminio/plane-uploads;
      exit 0;
      "
    networks:
      - plane_net

  plane-migrator:
    image: docker.io/makeplane/plane-backend:latest
    container_name: plane-migrator
    restart: "no"
    env_file: /media/large_disk/Projects/depoly/.env.plane
    command: ["/bin/sh", "-c", "echo 'Waiting 15s for DB...' && sleep 15 && ./bin/docker-entrypoint-migrator.sh"]
    depends_on:
      plane-db:
        condition: service_healthy
      plane-redis:
        condition: service_healthy
    networks:
      - plane_net

  plane-api:
    image: docker.io/makeplane/plane-backend:latest
    container_name: plane-api
    restart: always
    command: ./bin/docker-entrypoint-api.sh
    env_file: /media/large_disk/Projects/depoly/.env.plane
    depends_on:
      plane-db:
        condition: service_healthy
      plane-redis:
        condition: service_healthy
    networks:
      - plane_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  plane-worker:
    image: docker.io/makeplane/plane-backend:latest
    container_name: plane-worker
    restart: always
    command: ./bin/docker-entrypoint-worker.sh
    env_file: /media/large_disk/Projects/depoly/.env.plane
    depends_on:
      - plane-api
    networks:
      - plane_net

  plane-beat:
    image: docker.io/makeplane/plane-backend:latest
    container_name: plane-beat
    restart: always
    command: ./bin/docker-entrypoint-beat.sh
    env_file: /media/large_disk/Projects/depoly/.env.plane
    depends_on:
      - plane-api
    networks:
      - plane_net

  plane-web:
    image: docker.io/makeplane/plane-frontend:latest
    container_name: plane-web
    restart: always
    env_file: /media/large_disk/Projects/depoly/.env.plane
    command: node web/server.js
    depends_on:
      - plane-api
    networks:
      - plane_net

  plane-admin:
    image: docker.io/makeplane/plane-admin:latest
    container_name: plane-admin
    restart: always
    env_file: /media/large_disk/Projects/depoly/.env.plane
    command: node admin/server.js
    depends_on:
      - plane-api
    networks:
      - plane_net

  plane-proxy:
    image: docker.io/library/nginx:alpine
    container_name: plane-proxy
    restart: always
    ports:
      - "8090:80"
    volumes:
      - /media/large_disk/Projects/depoly/plane_data/nginx_conf/plane.conf:/etc/nginx/conf.d/default.conf:ro,Z
    depends_on:
      - plane-web
      - plane-api
      - plane-admin
    networks:
      - plane_net

networks:
  plane_net:
    driver: bridge
