version: '3.8'

services:
  plane-db:
    image: docker.io/library/postgres:15-alpine
    container_name: plane-db
    restart: always
    environment:
      POSTGRES_USER: plane
      POSTGRES_PASSWORD: plane_password
      POSTGRES_DB: plane
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./plane_data/pg_data:/var/lib/postgresql/data:Z
    networks:
      - plane_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plane -d plane"]
      interval: 10s
      retries: 5

  plane-redis:
    image: docker.io/library/redis:7-alpine
    container_name: plane-redis
    restart: always
    volumes:
      - ./plane_data/redis_data:/data:Z
    networks:
      - plane_net

  plane-minio:
    image: docker.io/minio/minio
    container_name: plane-minio
    restart: always
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: plane-admin
      MINIO_ROOT_PASSWORD: plane-secret-key-123
    volumes:
      - ./plane_data/minio_data:/data:Z
    networks:
      - plane_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: docker.io/minio/mc
    container_name: plane-createbuckets
    depends_on:
      - plane-minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://plane-minio:9000 plane-admin plane-secret-key-123;
      /usr/bin/mc mb myminio/plane-uploads || true;
      /usr/bin/mc anonymous set download myminio/plane-uploads;
      exit 0;
      "
    networks:
      - plane_net

  # 数据库迁移 (初始化表结构)
  plane-migrator:
    image: docker.io/makeplane/plane-backend:latest
    container_name: plane-migrator
    # 修复点：必须加引号，防止被解析为 False
    restart: "no"
    command: ./bin/docker-entrypoint-migrator.sh
    env_file: .env
    depends_on:
      - plane-db
      - plane-redis
    networks:
      - plane_net

  plane-api:
    image: docker.io/makeplane/plane-backend:latest
    container_name: plane-api
    restart: always
    command: ./bin/docker-entrypoint-api.sh
    env_file: .env
    depends_on:
      - plane-db
      - plane-redis
      # 移除严格条件，改为标准依赖。如果 migrator 还没跑完，API 会报错重启，直到成功。
      - plane-migrator
    networks:
      - plane_net

  plane-worker:
    image: docker.io/makeplane/plane-backend:latest
    container_name: plane-worker
    restart: always
    command: ./bin/docker-entrypoint-worker.sh
    env_file: .env
    depends_on:
      - plane-api
      - plane-db
      - plane-redis
    networks:
      - plane_net

  plane-beat:
    image: docker.io/makeplane/plane-backend:latest
    container_name: plane-beat
    restart: always
    command: ./bin/docker-entrypoint-beat.sh
    env_file: .env
    depends_on:
      - plane-api
      - plane-db
      - plane-redis
    networks:
      - plane_net

  plane-web:
    image: docker.io/makeplane/plane-frontend:latest
    container_name: plane-web
    restart: always
    env_file: .env
    # 修复点：不指定 command，使用镜像默认值，防止路径错误
    depends_on:
      - plane-api
    networks:
      - plane_net

  nginx:
    image: docker.io/library/nginx:alpine
    container_name: plane-proxy
    restart: always
    ports:
      - "8090:80"
    volumes:
      - ./plane_data/nginx_conf/plane.conf:/etc/nginx/conf.d/default.conf:ro,Z
    depends_on:
      - plane-web
      - plane-api
    networks:
      - plane_net

networks:
  plane_net:
    driver: bridge
